### ISSUE TITLE
[FEA] Add message_info support to get trace info in rclcpp.

### ISSUE THREAD

**Issue by ZhenshengLee** [continental/rmw_ecal#50]
In order to get ros2_tracing based performance test of rmw_ecal, there is needs that get message_info in rmw.

```cpp
    auto rmw_info = message_info.get_rmw_message_info();
    TRACEPOINT(rclcpp_subscribe, (const void *)this,
               rmw_info.source_timestamp, rmw_info.received_timestamp);
```

the message info includes: source_stamp, received_stamp ...

with these infos, the comm latency of the topic can be calculated.

currently message info is not filled.

see code snip here

https://github.com/continental/rmw_ecal/blob/5c92082a0f78d0ddb6d7e5c6d3f41faef5f79088/rmw_ecal_shared_cpp/src/rmw.cpp#L326-L334

**Comment by brakmic-aleksandar** [comment]
Good catch, I'll implement that feature!

But I'm not entirely sure whether its good idea to use them to calculate latency.
From [source](https://github.com/ros2/rmw/blob/690c72d09931d41d4a223bb64dbef4d3fc8a878d/rmw/include/rmw/types.h#L632):
```  
  /// Time when the message was published by the publisher.
  /**
   * The exact point at which the timestamp is taken is not specified, but
   * it should be taken consistently at the same point in the
   * publishing process each time.
   */
  rmw_time_point_value_t source_timestamp;
  /// Time when the message was received by the subscription.
  /**
   * The exact point at which the timestamp is taken is not specified, but
   * it should be taken consistently at the same point in the
   * process of receiving a message each time.
   */
  rmw_time_point_value_t received_timestamp; 
```
The exact time its being taken is not specified, which means it could be taken before or after serialization/deserialization, and depending on RMW implementation it could lead to inconsistencies in your calculations (or rather comparison). For example:
- If those times are taken at publish/receive times on underlying middleware layer, then comparing their subtracted differences will only show you the latency on middleware layer, rather than RMW layer (which can be quite the overhead, especially since it has to implement its own serialization/deserialization of messages).
- Also as stated since its RMW gets to decide at which point to take the timestamp (rather than time point being standardized) the comparisons might be invalid.

In my opinion it would be better to take timestamps, in app layer, before publishing and when subscriber receives the message, that way you should get consistent performance comparison for whole RWM stack.

**Comment by brakmic-aleksandar** [comment]
Hey, i've implemented timestamps. 
https://github.com/continental/rmw_ecal/pull/51

**Comment by brakmic-aleksandar** [comment]
Done!
